# Generated by Django 4.2.7 on 2024-05-08 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Boots/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Boots/', verbose_name='icon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carnice',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Carnice/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Carnice/', verbose_name='icon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(blank=True, max_length=128, null=True)),
                ('shape', models.CharField(blank=True, max_length=128, null=True)),
                ('bevel', models.CharField(blank=True, max_length=128, null=True)),
                ('molding', models.CharField(blank=True, max_length=64, null=True)),
                ('portal', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.CharField(blank=True, max_length=64, null=True)),
                ('carnice', models.CharField(blank=True, max_length=64, null=True)),
                ('podium', models.CharField(blank=True, max_length=64, null=True)),
                ('socket', models.CharField(blank=True, max_length=64, null=True)),
                ('boots', models.CharField(blank=True, max_length=64, null=True)),
                ('door_price', models.FloatField()),
                ('size', models.CharField(max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Podium',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Podium/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Podium/', verbose_name='icon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Portal/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Portal/', verbose_name='icon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shpon_Boots',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Boots/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Boots/', verbose_name='icon')),
                ('color', models.CharField(max_length=127)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shpon_Carnice',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Carnice/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Carnice/', verbose_name='icon')),
                ('color', models.CharField(max_length=127)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shpon_Socket',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Socket/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Socket/', verbose_name='icon')),
                ('color', models.CharField(max_length=127)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Socket/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Socket/', verbose_name='icon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniqueKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=108, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shpone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_type', models.CharField(max_length=127)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=127)),
                ('portal', models.CharField(max_length=127)),
                ('portal_image', models.ImageField(upload_to='Portals/')),
                ('image', models.ImageField(upload_to='Shape/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Shape/', verbose_name='icon')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
            ],
        ),
        migrations.CreateModel(
            name='Shpon_Molding',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Molding/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Molding/', verbose_name='icon')),
                ('color', models.CharField(max_length=127)),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_type', models.CharField(max_length=127)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('bevel', models.CharField(blank=True, max_length=127, null=True)),
                ('image', models.ImageField(upload_to='Shape/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Shape/', verbose_name='icon')),
                ('Grid_image', models.ImageField(blank=True, null=True, upload_to='Grid/', verbose_name='Grid Photo')),
                ('Grid_icon', models.ImageField(blank=True, null=True, upload_to='icon/Grid/', verbose_name='Grid Icon')),
                ('Bevel_icon', models.ImageField(blank=True, null=True, upload_to='icon/Bevel/', verbose_name='Bevel icon')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
            ],
        ),
        migrations.CreateModel(
            name='Molding',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Molding/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Molding/', verbose_name='icon')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
            ],
        ),
        migrations.AddIndex(
            model_name='collections',
            index=models.Index(fields=['name'], name='Main_collec_name_793d65_idx'),
        ),
        migrations.AddIndex(
            model_name='shpone',
            index=models.Index(fields=['collections'], name='Main_shpone_collect_f26b46_idx'),
        ),
        migrations.AddIndex(
            model_name='shpon_molding',
            index=models.Index(fields=['collections'], name='Main_shpon__collect_085ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='shape',
            index=models.Index(fields=['collections'], name='Main_shape_collect_750f30_idx'),
        ),
        migrations.AddIndex(
            model_name='molding',
            index=models.Index(fields=['collections'], name='Main_moldin_collect_1ea605_idx'),
        ),
    ]
