# Generated by Django 3.2.12 on 2024-04-13 12:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Boots/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Boots/', verbose_name='icon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carnice',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Carnice/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Carnice/', verbose_name='icon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_price', models.FloatField()),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('door_type', models.CharField(max_length=127)),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('bevel', models.CharField(blank=True, max_length=127, null=True)),
                ('image', models.ImageField(upload_to='Shape/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Shape/', verbose_name='icon')),
                ('Grid_image', models.ImageField(blank=True, null=True, upload_to='Grid/', verbose_name='Grid Photo')),
                ('Grid_icon', models.ImageField(blank=True, null=True, upload_to='icon/Grid/', verbose_name='Grid Icon')),
                ('Bevel_icon', models.ImageField(blank=True, null=True, upload_to='icon/Bevel/', verbose_name='Bevel icon')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Socket/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Socket/', verbose_name='icon')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.shape')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Portal/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Portal/', verbose_name='icon')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.shape')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Podium',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Podium/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Podium/', verbose_name='icon')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.shape')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Molding',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Molding/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Molding/', verbose_name='icon')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.shape')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='collections',
            index=models.Index(fields=['name'], name='Main_collec_name_793d65_idx'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='boots',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.boots'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='carnice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.carnice'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='molding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.molding'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='podium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.podium'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.portal'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.shape'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.socket'),
        ),
        migrations.AddField(
            model_name='carnice',
            name='collections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections'),
        ),
        migrations.AddField(
            model_name='carnice',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.shape'),
        ),
        migrations.AddField(
            model_name='boots',
            name='collections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections'),
        ),
        migrations.AddField(
            model_name='boots',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.shape'),
        ),
        migrations.AddIndex(
            model_name='socket',
            index=models.Index(fields=['collections'], name='Main_socket_collect_e61c98_idx'),
        ),
        migrations.AddIndex(
            model_name='shape',
            index=models.Index(fields=['collections'], name='Main_shape_collect_750f30_idx'),
        ),
        migrations.AddIndex(
            model_name='portal',
            index=models.Index(fields=['collections'], name='Main_portal_collect_0adedf_idx'),
        ),
        migrations.AddIndex(
            model_name='podium',
            index=models.Index(fields=['collections'], name='Main_podium_collect_c44671_idx'),
        ),
        migrations.AddIndex(
            model_name='molding',
            index=models.Index(fields=['collections'], name='Main_moldin_collect_1ea605_idx'),
        ),
        migrations.AddIndex(
            model_name='carnice',
            index=models.Index(fields=['collections'], name='Main_carnic_collect_84413b_idx'),
        ),
        migrations.AddIndex(
            model_name='boots',
            index=models.Index(fields=['collections'], name='Main_boots_collect_a1205b_idx'),
        ),
    ]
