# Generated by Django 5.0.3 on 2024-04-02 20:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Boots/', verbose_name='Изображение')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='Main_boots_name_3d234b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Carnice',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Carnice/', verbose_name='Изображение')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='Main_carnic_name_453e0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=127)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='Main_collec_name_793d65_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassicDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_type', models.CharField(max_length=127)),
                ('door_image', models.ImageField(upload_to='Door/', verbose_name='Изображение')),
                ('shape', models.CharField(max_length=127)),
                ('shape_price', models.FloatField()),
                ('door_price', models.FloatField()),
                ('Bevel', models.CharField(max_length=127)),
                ('boots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.boots')),
                ('carnice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.carnice')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassicBaguette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_type', models.CharField(max_length=127)),
                ('door_image', models.ImageField(upload_to='Door/', verbose_name='Изображение')),
                ('shape', models.CharField(max_length=127)),
                ('shape_price', models.FloatField()),
                ('door_price', models.FloatField()),
                ('Molding', models.CharField(max_length=127)),
                ('Molding_image', models.ImageField(upload_to='Molding/', verbose_name='Изображение')),
                ('boots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.boots')),
                ('carnice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.carnice')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_type', models.CharField(max_length=127)),
                ('door_image', models.ImageField(upload_to='Door/', verbose_name='Изображение')),
                ('shape', models.CharField(max_length=127)),
                ('shape_price', models.FloatField()),
                ('door_price', models.FloatField()),
                ('boots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.boots')),
                ('carnice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.carnice')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrigliaDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_type', models.CharField(max_length=127)),
                ('door_image', models.ImageField(upload_to='Door/', verbose_name='Изображение')),
                ('shape', models.CharField(max_length=127)),
                ('shape_price', models.FloatField()),
                ('door_price', models.FloatField()),
                ('Grid', models.CharField(max_length=127)),
                ('Grid_image', models.ImageField(upload_to='Grid/', verbose_name='Изображение')),
                ('Bevel', models.CharField(max_length=127)),
                ('boots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.boots')),
                ('carnice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.carnice')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.cart')),
                ('classic_baguette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.classicbaguette')),
                ('classic_door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.classicdoor')),
                ('base_door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.doors')),
                ('griglia_door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.grigliadoor')),
            ],
        ),
        migrations.CreateModel(
            name='Podium',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Podium/', verbose_name='Изображение')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='Main_podium_name_c0be6d_idx')],
            },
        ),
        migrations.AddField(
            model_name='grigliadoor',
            name='podium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.podium'),
        ),
        migrations.AddField(
            model_name='doors',
            name='podium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.podium'),
        ),
        migrations.AddField(
            model_name='classicdoor',
            name='podium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.podium'),
        ),
        migrations.AddField(
            model_name='classicbaguette',
            name='podium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.podium'),
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Portal/', verbose_name='Изображение')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='Main_portal_name_8e81ad_idx')],
            },
        ),
        migrations.AddField(
            model_name='grigliadoor',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.portal'),
        ),
        migrations.AddField(
            model_name='doors',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.portal'),
        ),
        migrations.AddField(
            model_name='classicdoor',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.portal'),
        ),
        migrations.AddField(
            model_name='classicbaguette',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.portal'),
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Socket/', verbose_name='Изображение')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='Main_socket_name_c18c69_idx')],
            },
        ),
        migrations.AddField(
            model_name='grigliadoor',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.socket'),
        ),
        migrations.AddField(
            model_name='doors',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.socket'),
        ),
        migrations.AddField(
            model_name='classicdoor',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.socket'),
        ),
        migrations.AddField(
            model_name='classicbaguette',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.socket'),
        ),
    ]
