# Generated by Django 3.2.12 on 2024-04-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boots',
            name='icon',
            field=models.ImageField(default='none.png', upload_to='icon/Boots/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='carnice',
            name='icon',
            field=models.ImageField(default='none.png', upload_to='icon/Carnice/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='classicbaguette',
            name='icon',
            field=models.ImageField(default='none.png', upload_to='icon/Molding/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='classicdoor',
            name='icon',
            field=models.ImageField(default='none.png', upload_to='icon/Bevel/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='doors',
            name='icon',
            field=models.ImageField(default='none.png', upload_to='icon/Door/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='grigliadoor',
            name='Bevel_icon',
            field=models.ImageField(default='none.png', upload_to='icon/Bevel/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='grigliadoor',
            name='icon',
            field=models.ImageField(default='none.png', upload_to='icon/Grid/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='podium',
            name='icon',
            field=models.ImageField(default='none.png', upload_to='icon/Podium/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='portal',
            name='icon',
            field=models.ImageField(default='none.png', upload_to='icon/Portal/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='socket',
            name='icon',
            field=models.ImageField(default='none.png', upload_to='icon/Socket/', verbose_name='Изображение'),
        ),
        migrations.AddIndex(
            model_name='classicbaguette',
            index=models.Index(fields=['collection'], name='Main_classi_collect_02119d_idx'),
        ),
        migrations.AddIndex(
            model_name='classicdoor',
            index=models.Index(fields=['collection'], name='Main_classi_collect_676a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='doors',
            index=models.Index(fields=['collection'], name='Main_doors_collect_d85bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='grigliadoor',
            index=models.Index(fields=['collection'], name='Main_grigli_collect_6116d6_idx'),
        ),
    ]
