# Generated by Django 3.2.12 on 2024-04-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='Bevel',
        ),
        migrations.AlterField(
            model_name='shape',
            name='Bevel_icon',
            field=models.ImageField(default='none.png', upload_to='icon/Bevel/', verbose_name='Bevel icon'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='Grid_icon',
            field=models.ImageField(default='none.png', upload_to='icon/Grid/', verbose_name='Grid Icon'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='Grid_image',
            field=models.ImageField(default='none.png', upload_to='Grid/', verbose_name='Grid Photo'),
        ),
    ]
