# Generated by Django 4.2.7 on 2024-04-30 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shpon_Molding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Molding/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Molding/', verbose_name='icon')),
                ('color', models.CharField(max_length=127)),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
            ],
            options={
                'indexes': [models.Index(fields=['collections'], name='Main_shpon__collect_085ecb_idx')],
            },
        ),
    ]
