# Generated by Django 3.2.12 on 2024-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='UniqueKey',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='Key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
