# Generated by Django 3.2.12 on 2024-04-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20240421_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='bevel',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
