# Generated by Django 4.2.7 on 2024-05-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_cartitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='icon',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
