# Generated by Django 3.2.12 on 2024-04-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_cartitem_bevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
