# Generated by Django 4.2.7 on 2024-06-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_cartitem_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='grid_bevel',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
