# Generated by Django 4.2.7 on 2024-04-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_cartitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shpon_Boots',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Boots/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Boots/', verbose_name='icon')),
                ('color', models.CharField(max_length=127)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shpon_Carnice',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Carnice/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Carnice/', verbose_name='icon')),
                ('color', models.CharField(max_length=127)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shpon_Podium',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Podium/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Podium/', verbose_name='icon')),
                ('color', models.CharField(max_length=127)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shpon_Socket',
            fields=[
                ('name', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Socket/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Socket/', verbose_name='icon')),
                ('color', models.CharField(max_length=127)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shpone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_type', models.CharField(max_length=127)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=127)),
                ('portal', models.CharField(max_length=127)),
                ('portal_image', models.ImageField(upload_to='Portals/')),
                ('image', models.ImageField(upload_to='Shape/', verbose_name='Photo')),
                ('icon', models.ImageField(upload_to='icon/Shape/', verbose_name='icon')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.collections')),
            ],
            options={
                'indexes': [models.Index(fields=['collections'], name='Main_shpone_collect_f26b46_idx')],
            },
        ),
    ]
