# Generated by Django 5.0.6 on 2024-06-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_cartitem_grid_bevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='molding_color',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
